version: 2
# === GitHub username to full name map ===
# robert-mcdermott - Robert McDermott - Scicomp Solutions Architect

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: true
  approve_regex: ^Approved
  reject_regex: ^Rejected
  conditions:
    branches:
      - master  # this group only reviews when PR is merging into master
    files:
      exclude:
        - '*.md'

groups:
  devops:
    required: 1
    reject_value: -2
    reset_on_push:
      enabled: true
    users:
      - robert-mcdermott


  security:
    required: 0
    reject_value: -100
    reset_on_push:
      enabled: false
    users:
      - robert-mcdermott

  managment:
      required: 0
      reject_value: -100
      reset_on_push:
        enabled: false
      users:
        - robert-mcdermott
