version: '2'
services:
  countdown2cure-lb:
    image: rancher/lb-service-haproxy:v0.4.9
    ports:
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  countdown2cure:
    image: dockerhub.fhcrc.org/countdown2cure:latest
    ports:
    - 80/tcp
    labels:
      io.rancher.container.pull_image: always
